[project]
name = "talk-souravtripathy-backend"
version = "0.1.0"
description = "FastAPI + Inference Backend for talk.souravtripathy.com"
requires-python = ">=3.12,<3.13"

dependencies = [
    "fastapi>=0.111.0",
    "uvicorn[standard]>=0.29.0",
    "vllm-cpu",
    "psutil>=5.9.0",
    "torch>=2.2.0",
    "python-dotenv>=1.0.0",
    "pydantic>=2.6.0",
    "transformers>=4.45.0,<5.0.0",
    "setuptools",
    "sglang>=0.5.2",
    "sgl-kernel>=0.3.21",
]

[project.scripts]
# Start the server with: uv run serve
serve = "uvicorn main:app --host 0.0.0.0 --port 8000 --reload false"

[tool.uv]
# uv will create .venv inside the backend directory
# Run the app with:  uv run python main.py
# Install deps with: uv sync
environments = ["sys_platform == 'linux' and platform_machine == 'x86_64' and python_version == '3.12'"]
index-strategy = "unsafe-best-match"


[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = false


